### ISSUE TITLE
Different sound at same parameter values. 

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#2051] opened 2020-07-06 19:44 UTC
Hi I got a problem at some presets:

**Preconditions :**
    Using _old_ presets converted to the new MS 1.7 beta (based on RELEASE-2020-06) 

    I attached a bank with two presets : 
    1 - "wumsongo 3"  MC-B(Pedal-2)          is used for FB Mix (Osc-A)
    2 - "first flute 3"      MC A(Pedal-1)          is used for FB Mix (Osc-A)
    both examples have pedals set to non-returning

**Issue:**
   **Preset 1:**
       Modulate Pedal-2 (MC-B) to maximum FB Mix goes up to value 17.9 
       Play sound -> lots of  Feedback to hear 
       Adjust FB Mix           to 18.0 (fine + inc by one)
       Adjust FB Mix back  to 17.9 (fine + dec by one)
       Play sound -> Feedback sounds much smaller

   **Preset 2:**
       Modulate Pedal 1 (MC-A) to minimum. => FB MIx  = 12.2 %
       Play sound and remember the decay length for later
       Modulate Pedal-1 (MC-A) to maximum FB Mix goes up to value 87.5 %
       Play sound ->  hear nothing cause feedback is to high 
       Adjust FB Mix                 to 87.6 %(fine + inc by one)
       Adjust FB Mix back        to 87.5 % (fine + dec by one)
       Play sound -> Feedback is like it should be.
       Now modulate Pedal 1 back minimum => FB Mix = 12.2
       Play sound -> Sound differs much to remembered from beginning.

Could be something by sound conversion or by MC Amounts.
Saving of the presets does not change the behaviour.
 
Any ideas ?

[New Bank (2).xml.zip](https://github.com/nonlinear-labs-dev/C15/files/4880923/New.Bank.2.xml.zip)

**Comment by MatthiasSeeber** [comment] 2020-07-07 09:38
I agree this is odd. Possible bugs could be conversion issue, mod amounts, maybe even flaws in the new 1.7 FB routing/application?

**Preset 1**

- when first increasing the FB Mix from 0.1 to 0.2 and then modulating, the issue seems to disappear, sounding right after increasing Pedal 2 (to MC B) to 100%
- when following the above instruction (Pedal 2 to 100%), and then playing and **holding** a (FB-rich) sound, then increasing FB Mix from 17.0 to 18.0, an interesting effect is audible (seemingly exposing the somehow gradual loss of FB - oddly sounding like reducing a strong shaper drive)

**Preset 2**

- first increasing the FB Mix by 0.1 does not produce any different effect
- holding a pressed key while following the instruction does not help (sound seems to be upheld only by Comb FB)

@majjam can you provide the original Bank used with the C15 Milestone 1.5? (The provided bank already is converted to 1.7.)

I think it would be useful to compare the behaviors of the two systems against each other.

**Comment by majjam** [comment] 2020-07-07 11:38
@MatthiasSeeber 
Your inspection is correct as it gives me the same results (if i remember correctly)

I will have a look at my backups this evening:
Possibly there will be my complete banksetup as backup . Then i will guide you to the corresponding banks and presetnumbers.

Small notice : 
Preset 2 formerly was saved as "first flute 2"
There was MC-B connected to unision detune.  Soundwise the unision pitch was modulated by a complete octave.  After conversion the value was set to 6, with corresponding sound (half octave only)

**Comment by MatthiasSeeber** [comment] 2020-07-07 11:52
Thanks in advance! Backups should be fine.

**Comment by majjam** [comment] 2020-07-07 14:19
Luckily found it as a single bank file ;)

[2020-06-025-Selfmade Millionaire.zip](https://github.com/nonlinear-labs-dev/C15/files/4885340/2020-06-025-Selfmade.Millionaire.zip)
Mentioned presets should be 147 and 168
Bank Version is 5 (while actual exports show Bank Version 8)
i hope this helps

**Comment by MatthiasSeeber** [comment] 2020-07-07 14:46
Great, thanks! This should suffice, I will be on it within the next days.

And yes btw, Banks are converted when they are loaded (for example when imported or during startup) and an export always contains the latest version.

**Comment by majjam** [comment] 2020-07-07 15:41
Didn't doubt that export results in the latest bank version. 
That was for the files only (V5 -> V8)

**Comment by MatthiasSeeber** [comment] 2020-07-07 15:46
Maybe I misread, sry. Anyway, V5 is _exactly_ what I need for comparison.

**Comment by majjam** [comment] 2020-07-14 17:15
@MatthiasSeeber 
for your info : i have another easy hearable example in the attached bank:
162 Sakralorgel 3 : 
1. load preset 
2. play tone and remember sound (FB Mix of Osc B is at value 46.6)
3. modulate Pedal 2 (MCB) to 0
4. increase FB Mix of Osc B by 0.1 to 0.1
5. decrease FB Mix of Osc B by 0.1 back to 0.0
6. modulate pedal 2 (MCB) back to maximum (46.6)
7. play note and compare to remembered sound.

**Comment by MatthiasSeeber** [comment] 2020-07-15 10:38
@majjam
Thanks for providing further test possibilities, I will test the preset as soon as I can. What I did find out so far is, that there definitely are some issues regarding the modulation, resulting in differences between the Milestones 1.5 and 1.7. I'm on it..

**Comment by MatthiasSeeber** [comment] 2020-07-15 12:30
I tested wumsongo and first flute out of my IDE (**only 1.7**) and seemingly, PR #2074 fixes the issue. I so far have not tested, if the behavior **really** is similar to **1.5**, though - but it seems right to me.

**Comment by majjam** [comment] 2020-07-15 17:31
hi, thanks for keeping me updated !
I had a view to PR #2074 and audited my presets :

_147 First flute 2:_
This preset is now perfectly close if not the equal to what I remember from the 'old' engine.
changing the FB Mix like described above does not show any faults
   
_162 Sakralorgel 3 :_ 
This preset is now perfectly close if not the equal to what I remember from the 'old' engine.
changing the FB Mix like described above does not show any faults

_167: Wumsongo 3:_
This preset is equal FB-wise
changing the FB Mix like described above does not show any faults
**But.. somehow the decay of the sound if Pedal 4 (MC-D) is triggered seems to be too short.**
This can be a deception. If not it could have to do with Comb filters decay or gate OR with Reverb settings somehow.

From my side this issue can be closed as the FB Mix-Problem has been gone.
Shall I open a new ticcket for the sound decay (maybe-)issue ?
Or will you have a preset comparison first ?

**Comment by MatthiasSeeber** [comment] 2020-07-15 17:44
Thanks for testing and verifying the fix!
I'd suggest to keep the potential decay issue separate.

The PR is already considered a hotfix and should result in an official update.tar pretty soon. (It also fixes the Shaper Mix params, which were buggy in a similar way)

So when the PR is merged, this issue can be closed. I don't know exactly when I will be in the office to test the Wumsongo behavior on old and new devices, but if I can confirm differences, I will open a new ticket.

**Comment by majjam** [comment] 2020-07-16 07:03
thanks for your effort !
Especially for 162 i am very happy to have the originally tweaked sound back.

**Comment by AntonSchmied** [comment] 2020-07-16 09:17
> _167: Wumsongo 3:_
> **But.. somehow the decay of the sound if Pedal 4 (MC-D) is triggered seems to be too short.**
We setup two C15, one with 1.5 and one with 1.7+PR2074, and we were not really able to determine a difference between the decay behaviors. We can keep this in mind just in case and @MatthiasSeeber you can double check it, once you're in office. your call

**Comment by MatthiasSeeber** [comment] 2020-07-16 09:48
With the merge of #2074 this issue can be closed.

**Closed by MatthiasSeeber** 2020-07-16 09:48 UTC
