### ISSUE TITLE
WebUI: Die HW Amounts werden, auch wenn sie Schalter sind, in der Bauchbinde als kontinuierlich dargestellt/bedient.

### ISSUE THREAD

**Issue by nonlinear-labs** [nonlinear-labs-dev/C15#1588] opened 2020-03-18 22:05 UTC

**Comment by MatthiasSeeber** [comment] 2020-03-19 07:59
this is a duplicate of #1503

**Comment by MatthiasSeeber** [comment] 2020-04-03 14:17
I'm sorry, but I can't verify the Bug Fix:

![Screenshot from 2020-04-03 16-14-52](https://user-images.githubusercontent.com/37212609/78370061-6e234100-75c6-11ea-8183-8d610295d2b0.png)

Using master (`commit a371389b0093b161fc3b7194977b5bb5f37f0a82`), I can still slide through the HW Amount in the WebUI, although it should be switch-like (on/off). The HWUI behaves correctly.

**Comment by MatthiasSeeber** [comment] 2020-04-03 16:44
Using master (`commit 4eb2986`) yields the same, wrong results.

**Closed** 2020-04-06 12:11 UTC
Labels: Reconsider Issue, bug
