### ISSUE TITLE
FX assignment at split sound creation [NOT a  bug  nor wrong behavior]

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/C15#3455] opened 2022-12-25 11:11 UTC
tested on issue-2995-ui @ c78d1b49d 

OK: 
(all done via  HWUI)
1.  convert sound to split sound => all sounds ok
2. select load to part
3. select **right layer and assign new sound** (select fx 1 or 2 like you want )
4.  everything sound ok to me

BUG: 
1.  convert sound to split sound => all sounds ok
2. select load to part
3. select **left layer and assign new sound** (select fx 1 or 2 like you want )
4. play "right" sound while changing through the left sounds : 
5.  the fx of the left sound are assigned to the right ones
sometimes left sound is inaudible .(through the wrong fx selection ?)

btw MERRY CHRISTMAS AND HAVE SOME ENJOYABLE DAYS

**Comment by MatthiasSeeber** [comment] 2023-01-02 15:03
Thank you for eagerly testing and a happy new year to you!

I am not sure if your observations describe a bug in accordance to our rule-set, but I can see that this doesn't feel right. Here some clarification:

> 1. convert sound to split sound => all sounds ok

There is a bug in the Sound conversion (which I ammended to the corresponding [PR](https://github.com/nonlinear-labs-dev/C15/pull/3435#pullrequestreview-1233827515)) - besides: If you convert a typical Single Sound to Split/Layer, Part II will (should) be muted - as visible in the Sound Screen. This is because of the new Single Master > FX Mix parameter, crossfading between FX I and II and initializing to 0% (FX I go 100% to out, FX II are effectively muted). The initial state reflects the "old" behavior with only one FX chain. So typically, converting a Single Sound to Split/Layer should result in only Part I as audible/usable sound source.

If converting a Single Sound with FX Mix greater than 0%, both Parts should have Volumes greater than -inf. Furthermore, typical "old" Single Sounds also have a Output Mixer > To FX parameter at 0%, routing everything exclusively to FX I.

> 5. the fx of the left sound are assigned to the right ones

This is most likely an illusion. The converted sound has Part II with Output Mixer > To FX going fully to FX I (as described above). When loading another Sound into Part I, FX I will be overwritten. As Part II also feeds FX I, it seems that it's FX have been overwritten.

> 5. sometimes left sound is inaudible .(through the wrong fx selection ?)

This can happen to both Parts (left/right == I/II). I am not 100% certain at the moment, but I suspect that the above described FX Mix is responsible and produces a loaded Part with an -inf Volume.

---

So all in all, there are many subtle things to consider with Load To Part (and also Convert) and I'm pretty sure that not everything will be intuitively clear to the user. But maybe, we can do more to at least indicate if a Single "Part" is muted when trying to load it, or maybe even extending the rule-set somehow..

**Comment by majjam** [comment] 2023-01-02 16:27
Hi Matthias ,
happy new year !

I will need some time to really understand and check  your answers - thanks for them.
When i find the time i will sketch my estimations for the conversions results . Perhaps an outside user view can help to uncover potential  problems.
I hope i ll find the time next days.

**Comment by majjam** [comment] 2023-01-02 19:33
Hi @MatthiasSeeber ,
I had an additional small test with the sound conversion rules.
Now being aware of your explanations everything is logical. And with that knowledge  magically my estimation and reality match!

What i did stumble over was the behavior you described : 

> There is a bug in the Sound conversion (which I ammended to the corresponding https://github.com/nonlinear-labs-dev/C15/pull/3435#pullrequestreview-1233827515) - besides: If you convert a typical Single Sound to Split/Layer, Part II will (should) be muted - ....

Single to split  conversion of "to FX I /II"-value  seems to be wrong the "serial FX"-value just as well .
Because you are already aware of this the issue can be closed.

thanks for clarifying 
Max

**Comment by MatthiasSeeber** [comment] 2023-01-03 10:34
Hey @majjam, feel free to reopen this issue if the following doesn't match your observations:

> Single to split conversion of "to FX I /II"-value seems to be wrong the "serial FX"-value just as well .

I can't confirm and observe correct behavior.

When converting Single to Split or Layer, the following happens:
- the polyphonic section (Env A/B/C ... FB/Out Mix) is essentially transferred to both target Parts I and II, with a few special rules [^1]
- the monophonic section (FX: Flanger ... Reverb) is transferred `I --> I` and `II --> II`
- global stuff (Master, Scale) is simply copied, except for [^2]

[^1]: Output Mixer > To FX I-II and Feedback Mixer > FX From I-II are transfered as `pos --> I` and `1-pos --> II`, essentially maintaining the FX routing from the Single Source

[^2]: Master: Volume, Tune: are transferred into Part Volume/Tune, FX Mix (only available in Single) is converted and "added" onto both Part Volumes I/II (only available in Split/Layer)

So, take a typical Single Sound with
- Master > FX Mix I-II = 0% (exclusively FX I)
- Output Mixer > To FX I-II = 0% (exclusively FX I)
- Feedback Mixer > From FX I-II = 0% (exclusively FX I)

and convert into Split (or Layer)
- Part > [I] Volume = -2.5 dB and [II] Volume = -inf dB (display correct: exclusively Part I, but known **bug**: sound wrong - both Parts audible, slider I influences both I and II)
- Output Mixer > [I] To FX II = 0% (exclusively Part I) and [II] To FX I = 100% (exclusively Part I)
- Feedback Mixer [I] From FX II = 0% (exclusively Part I) and [II] From FX I = 100% (exclusively Part I)

**Closed by MatthiasSeeber** 2023-01-03 10:34 UTC

**Comment by majjam** [comment] 2023-01-03 11:54
@MatthiasSeeber 
im not at the device  but if I remeber right I observed following :

starting from single sound  with  :
 - Master > Serial FX  = +50% 
 - Output Mixer > To FX I-II = 50%

conversion to split results in  :
 - Output Mixer > To FX II = 0% 
 - Serial FX = 0%

This feels wrong to me.

I did not consider the feedback parameters.

**Comment by MatthiasSeeber** [comment] 2023-01-03 12:00
Thanks! I can confirm that Master > Serial FX and FX Pan are in fact resetted when converting Single --> Dual. Output and FB Mixer routings are correct though.
